name: Pytest & Coverage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  run-testing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Just
        uses: extractions/setup-just@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev

      - name: Run tests with coverage
        run: |
          poetry run coverage run --source=torchcam --omit="*/__*.py,*/test_*.py" -m pytest
          poetry run coverage report -m > coverage.txt

      - name: Create GHA job summary
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
          echo "# Torchcam Testing Report [${TIMESTAMP}"] >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Pytest coverage" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          cat coverage.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
